config/routes.rb
Rails.application.routes.draw do
  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
  }
  
  #ユーザー用
  devise_for :users, skip: [:password], controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
  }
  #ゲストログイン用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
   get "/" => "homes#top"
   resources :reports, only: [:index, :show, :update]
   resources :users, only: [:index, :show, :edit, :update]
   resources :posts, only: [:index, :show, :destroy] do
     resources :post_comments, only: [:show, :destroy]
   end
   get "search" => "searches#search"
   resources :categories, only: [:index, :create, :edit, :destroy, :update, :destroy]
  end
  
  scope module: :public do
   root "homes#top"
   get "about" => "homes#about"
   #退会処理
   patch "users/withdraw" => "users#withdraw"
   resources :users, only: [:show, :edit, :update] do
     member do
      get :favorites 
     end
     resources :reports, only: [:new, :create]
    end
   resources :posts, only: [:new, :index, :show, :create, :destroy, :update, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
   end
   get "search" => "posts#search_name"
   get "/category/search" => "searches#search_category"
   #通知機能
   resources :notifications, only: [:index, :destroy]
  end
  
   
end

app/models/post.rb
class Post < ApplicationRecord
 belongs_to :user
 has_many :post_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :favorited_users, through: :favorites, source: :user
 belongs_to :category
 #通知機能
 has_one :notification, as: :subject, dependent: :destroy
 
 validates :title, presence: true
 validates :body, presence: true
 
 scope :latest, -> {order(created_at: :desc)}
 scope :old, -> {order(created_at: :asc)}
 scope :most_favorited, -> { includes(:favorited_users)
  .sort_by { |x| x.favorited_users.includes(:favorites).size }.reverse }
 
 def favorited_by?(user)
  favorites.exists?(user_id: user.id)
 end
 
  def self.search(content)
    Post.where("body LIKE? or title LIKE?","%#{content}%", "%#{content}%")
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
   before_action :authenticate_admin!
   
  def index
    @posts = Post.page(params[:page])
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<h1>Admin::Posts#index</h1>
<p>Find me in app/views/admin/posts/index.html.erb</p>

app/views/admin/posts/show.html.erb
<div class = "container mt-4">
    <h2 class="mt-4"> <span class="bg-dark text-light">投稿詳細</span></h2>
    
   <div class="border border-dark">
    <div class="row mt-4 w-100 ml-3">
        <%= image_tag @post.user.get_profile_image(50,50) %>
        <%= link_to admin_user_path(@post.user_id), class:"text-warning pt-2 pl-1" do %>
         <%= @post.user.name %>
        <% end %>
    </div>
    
    <div class="row mt-3">
     <div class="col-md-8">
        <h3><span class="bg-secondary ml-3">タイトル</span> <%= "" %> <%= @post.title %></h3>
     </div>
    </div>
    
    <div class="row mt-3  border-dark">
     <div class="col-md-8 border-dark d-flex">
        <h3 class="w-25 mt-2"><span class="bg-secondary ml-3">内容</span></h3>　<h4 class="border border-dark bg-light"><span><%= @post.body %></span></h4>
     </div>
    </div>
   </div>
    
    <div class="row mt-3 text-center">
      <%= link_to "削除する", admin_post_path, method: :delete, class:"btn btn-danger ml-4", data: {confirm: "投稿を削除しますか？"} %>
    </div>
    <small>投稿日：<%= @post.created_at.strftime('%Y/%m/%d') %></small>
    
    <div id="comment_index"><%= render "admin/post_comments/index", post: @post %></div>
</div>