config/routes.rb
Rails.application.routes.draw do
  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
  }
  
  #ユーザー用
  devise_for :users, skip: [:password], controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
  }
  #ゲストログイン用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
   get "/" => "homes#top"
   resources :reports, only: [:index, :show, :update]
   resources :users, only: [:index, :show, :edit, :update]
   resources :posts, only: [:index, :show, :destroy] do
     resources :post_comments, only: [:show, :destroy]
   end
   get "search" => "searches#search"
   resources :categories, only: [:index, :create, :edit, :destroy, :update, :destroy]
  end
  
  scope module: :public do
   root "homes#top"
   get "about" => "homes#about"
   #退会処理
   patch "users/withdraw" => "users#withdraw"
   resources :users, only: [:show, :edit, :update] do
     member do
      get :favorites 
     end
     resources :reports, only: [:new, :create]
    end
   resources :posts, only: [:new, :index, :show, :create, :destroy, :update, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
   end
   get "search" => "posts#search_name"
   get "/category/search" => "searches#search_category"
   #通知機能
   resources :notifications, only: [:index, :destroy]
  end
  
   
end

app/models/category.rb
class Category < ApplicationRecord
 has_many :posts

 validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
   before_action :authenticate_admin!
   
  def index
    @categories = Category.all
    @category =   Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
     redirect_to admin_categories_path
    else
     render 'edit'
    end
  end
  
  def destroy 
    category = Category.find(params[:id])
    category.destroy
    redirect_to admin_categories_path
  end

  def create
    @categories = Category.all
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path
    else
      render :index
    end
  end
  
  private
  
  def category_params
   params.require(:category).permit(:name)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container px-sm-0 px-5 mr-3" >
  <div class="row my-4">
    <h3><span class="bg-dark text-light">カテゴリー編集</span></h3>
  </div>
  <div class="row px-sm-0 px-5">
    <div class="col-md-8 px-5 px-sm-0">
      <%= render "admin/shared/error_messages", resource: @category %>
      <%= form_with model: @category, url: admin_category_path(@category.id), method: :patch do |f| %>
      <table class="table table-borderless">
        <tbody>
            <tr>
              <th>カテゴリー名</th>
              <td><%= f.text_field :name, class:"form-control" %></td>
              <td><%= f.submit '変更を保存', class:"btn btn-success" %></td>
              <td></td>
            </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>

app/views/admin/categories/index.html.erb
<div class="container px-sm-0 px-5 w-100 mr-4">
  <div class="row my-4">
    <h3><span class="bg-dark text-light">カテゴリー一覧・追加</span></h3>
  </div>
  <div class="row px-sm-0 px-5">
    <div class="col-md-6 px-5 px-sm-0">
      <%= render "admin/shared/error_messages", resource: @category %>
      <%= form_with model: @category, url: admin_categories_path do |f| %>
      <table class="table table-border border-dark">
        <tbody>
            <tr>
              <th>カテゴリー名</th>
              <td><%= f.text_field :name, class:"form-control" %></td>
              <td><%= f.submit '新規作成', class:"btn btn-success" %></td>
              <td></td>
            </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>

  <div class="row px-sm-0 px-5">
    <div class="col-md-5 px-5 px-sm-0">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th>カテゴリー</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= link_to "編集する", edit_admin_category_path(category), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "削除する", admin_category_path(category), method: :delete, class: "btn btn-sm btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>