config/routes.rb
Rails.application.routes.draw do
  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
  }
  
  #ユーザー用
  devise_for :users, skip: [:password], controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
  }
  #ゲストログイン用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
   get "/" => "homes#top"
   resources :reports, only: [:index, :show, :update]
   resources :users, only: [:index, :show, :edit, :update]
   resources :posts, only: [:index, :show, :destroy] do
     resources :post_comments, only: [:show, :destroy]
   end
   get "search" => "searches#search"
   resources :categories, only: [:index, :create, :edit, :destroy, :update, :destroy]
  end
  
  scope module: :public do
   root "homes#top"
   get "about" => "homes#about"
   #退会処理
   patch "users/withdraw" => "users#withdraw"
   resources :users, only: [:show, :edit, :update] do
     member do
      get :favorites 
     end
     resources :reports, only: [:new, :create]
    end
   resources :posts, only: [:new, :index, :show, :create, :destroy, :update, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
   end
   get "search" => "posts#search_name"
   get "/category/search" => "searches#search_category"
   #通知機能
   resources :notifications, only: [:index, :destroy]
  end
  
   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :reports, class_name: "Report", foreign_key: "reporter_id", dependent: :destroy
  has_many :reverse_of_reports, class_name: "Report", foreign_key: "reported_id", dependent: :destroy
  
  validates :name, presence: true
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def get_profile_image(width, height)
   unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
   profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def active_for_authentication?
    super && (self.is_active == true)
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
   before_action :authenticate_admin!
   
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @categories = Category.all
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end
  
  def user_params
    params.require(:user).permit(:is_active)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<div class="container mt-5">
   <div classs="row justify-content-center">
    <div class="col-md-10">
        <h2><span class="bg-dark text-light" >ユーザ一覧</span></h2>
        <table class="table table-hover table-inverse", style="table-layout:fixed;width:100%;">
         <thead>
          <tr>
           <th style="width:33%;">プロフィール画像</th>
           <th style="width:33%;">名前</th>
           <th style="width:33%;">いいね件数</th>
           <th style="width:33%;">ユーザーステータス</th>
           <th colspan="3"></th>
          </tr>
         </thead>
         
         <tbody>
          <% @users.each do |user| %>
          <tr>
          <td style="width:33%;">
              <%= link_to admin_user_path(user.id), class:"text-warning" do %>
              <%= image_tag user.get_profile_image(100,100) %><br>
              <%= user.name %>
              <% end %>
          </td>
          <td style="width:33%;"><%= user.name %></td>
          <td style="width:33%;"><%= user.favorites.count %>件</td>
           <% if user.is_active == true %>
            <td><strong style="color: green;">有効</strong></td>
           <% else %>
            <td><strong style="color: red;">退会済</strong></td>
           <% end %>
          </tr>
          <% end %>
          <%= paginate @users %>
         </tbody>
        </table>
    </div>
   </div>
 </div>

app/views/admin/users/show.html.erb
<div class="container mt-3"> 
   
        <div class="row mt-4 ml-5">
            <div class="col-md-3 offset-md-3">
             <h3 class="ml-4"><span class="bg-dark text-light">ユーザー情報</span></h3> 
            </div>
        </div>
    <div class="row mt-3">
        <div class="col-md-8 offset-md-1">
            <table class="table table-border table-dark">
                <tr>
                    <td class="text-center pt-4">プロフィール画像</td>
                    <td><%= image_tag @user.get_profile_image(50,50) %></td>
                </tr>
                <tr>
                    <td class="text-center">名前</td>
                    <td><%= @user.name %></td>
                </tr>
                <tr>
                    <td class="text-center">自己紹介</td>
                    <td><%= @user.introduction %></td>
                </tr>
            </table>
            <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch, local: true do |f| %>
            <tr>
              <th><%= f.label :is_active, "ユーザステータス" %></th>
              <td>
                <%= f.radio_button :is_active, true %>
                <strong><%= f.label :is_active_true, "有効"%></strong>
                <%= "　　"%>
                <%= f.radio_button :is_active, false %>
                <strong style="color: gray;"><%= f.label :is_active_false, "退会"%></strong>
              </td>
            </tr>
            <div class="text-right"><%= f.submit "編集内容を保存", class: "btn btn-danger text-right" %></div>
            <% end %>
             
             <div class="text-right"><%= link_to favorites_user_path(@user) do %>
                                     <%= @user.name %>さんのいいね投稿一覧
                                     <% end %>
             </div>
        </div>
    </div>
</div>