config/routes.rb
Rails.application.routes.draw do
  #管理者用
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: "admin/sessions"
  }
  
  #ユーザー用
  devise_for :users, skip: [:password], controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
  }
  #ゲストログイン用
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  namespace :admin do
   get "/" => "homes#top"
   resources :reports, only: [:index, :show, :update]
   resources :users, only: [:index, :show, :edit, :update]
   resources :posts, only: [:index, :show, :destroy] do
     resources :post_comments, only: [:show, :destroy]
   end
   get "search" => "searches#search"
   resources :categories, only: [:index, :create, :edit, :destroy, :update, :destroy]
  end
  
  scope module: :public do
   root "homes#top"
   get "about" => "homes#about"
   #退会処理
   patch "users/withdraw" => "users#withdraw"
   resources :users, only: [:show, :edit, :update] do
     member do
      get :favorites 
     end
     resources :reports, only: [:new, :create]
    end
   resources :posts, only: [:new, :index, :show, :create, :destroy, :update, :edit] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
   end
   get "search" => "posts#search_name"
   get "/category/search" => "searches#search_category"
   #通知機能
   resources :notifications, only: [:index, :destroy]
  end
  
   
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
 has_many :posts

 validates :name, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
 belongs_to :user
 belongs_to :post
 
 has_one :notification, as: :subject, dependent: :destroy
 after_create_commit :create_notifications
 
 private
  def create_notifications
    Notification.create(subject: self, user: self.post.user, action_type: :favorited_to_own_post)
  end
  
end

app/models/notification.rb
class Notification < ApplicationRecord
    
 belongs_to :subject, polymorphic: true
  belongs_to :user
  
  enum action_type: { commented_to_own_post: 0, favorited_to_own_post: 1 }
end

app/models/post.rb
class Post < ApplicationRecord
 belongs_to :user
 has_many :post_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :favorited_users, through: :favorites, source: :user
 belongs_to :category
 #通知機能
 has_one :notification, as: :subject, dependent: :destroy
 
 validates :title, presence: true
 validates :body, presence: true
 
 scope :latest, -> {order(created_at: :desc)}
 scope :old, -> {order(created_at: :asc)}
 scope :most_favorited, -> { includes(:favorited_users)
  .sort_by { |x| x.favorited_users.includes(:favorites).size }.reverse }
 
 def favorited_by?(user)
  favorites.exists?(user_id: user.id)
 end
 
  def self.search(content)
    Post.where("body LIKE? or title LIKE?","%#{content}%", "%#{content}%")
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
 belongs_to :user
 belongs_to :post
 
 has_one :notification, as: :subject, dependent: :destroy
 after_create_commit :create_notifications
 
 validates :comment, presence: true

  private
  
  def create_notifications
    Notification.create(subject: self, user: post.user, action_type: :commented_to_own_post)
  end
end

app/models/report.rb
class Report < ApplicationRecord
 
 belongs_to :reporter, class_name: "User"
 belongs_to :reported, class_name: "User"
 
 enum status: { waiting: 0, keep: 1, finish: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :reports, class_name: "Report", foreign_key: "reporter_id", dependent: :destroy
  has_many :reverse_of_reports, class_name: "Report", foreign_key: "reported_id", dependent: :destroy
  
  validates :name, presence: true
  
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def get_profile_image(width, height)
   unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
   profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def active_for_authentication?
    super && (self.is_active == true)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    
def top
end

def about
end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
   before_action :authenticate_admin!
   
  def index
    @posts = Post.page(params[:page])
    @categories = Category.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
   before_action :authenticate_admin!
   
  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @categories = Category.all
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end
  
  def user_params
    params.require(:user).permit(:is_active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Admin)
      admin_posts_path
    else
      posts_path
    end
  end
  
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      root_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end
  
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :is_active ])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_search.html.erb
<div class="form-inline">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
   <div class="input-group">
     <%= text_field_tag :content, params[:content], placeholder: "投稿を検索", class: "form-control" %>
      <span class="input-group-btn">
       <%= button_tag "検索", class: "btn bg-white" %>
      </span>
   </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FPS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/76f838f2af.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
      <div class="container">
        <a class="navbar-brand" href="/">
          <%= image_tag asset_path("icons8-fps-64.png"), width: '120px' %>
        </a>
          <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
            <p class="text-weight-bold"><span class="bg-light mr-4">管理者用ページ</span></p>
              <li class='nav-item'>
                <%= link_to '投稿一覧', admin_posts_path, class: 'btn btn-light mr-2' %>
              </li>
              <li class='nav-item'>
                <%= link_to 'ユーザ一覧', admin_users_path, class: 'btn btn-light mr-2' %>
              </li>
              <li class='nav-item'>
                <%= link_to 'カテゴリー一覧', admin_categories_path, class: 'btn btn-light mr-2' %>
              </li>
              <li class='nav-item'>
                <%= link_to '通報一覧', admin_reports_path, class: 'btn btn-light mr-2' %>
              </li>
              <li class='nav-item'>
                <%= link_to 'ログアウト', destroy_admin_session_path, class: 'btn btn-light' %>
              </li>
            <% elsif user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user), class: 'btn btn-light' do %>
                <span><i class="fa-solid fa-user fa-bounce"></i>マイページ</span>
                <% end %>
              </li>
              <li class="nav-item ml-2">
                <%= link_to posts_path, class: "btn btn-light" do %>
                <span><i class="fa-solid fa-book fa-beat"></i>投稿一覧</span>
                <% end %>
              </li>
              <li class="nav-item ml-2">
                <%= link_to  new_post_path, class: "btn btn-light" do %>
                <span><i class="fa-solid fa-marker fa-shake"></i>投稿する</span>
                <% end %>
              </li>
              <li class="nav-item ml-2">
                <%= link_to notifications_path, class: "btn btn-light" do %>
                  <% if current_user.notifications.where(checked: false).exists? %>
                   <i class="fa-sharp fa-solid fa-bell fa-beat" style="color: #f2ee7d;"></i>
                  <% else %>
                   <i class="fa-sharp fa-solid fa-bell"></i>
                   <% end %>
                   通知一覧
                <% end %>
              </li>
              <li class="nav-item ml-2">
                <%= link_to destroy_user_session_path, class: "btn btn-light mr-3" do %>
                <span><i class="fa-solid fa-right-from-bracket"></i>ログアウト</span>
                <% end %>
              </li>
              <%= render "layouts/search" %>
            <% else %>
              <li class="nav-item mr-2">
                <%= link_to 'About', about_path, class: "btn btn-light" %>
              </li>
              <li class="nav-item mr-2">
                <%= link_to '投稿一覧', posts_path, class: "btn btn-light" %>
              </li>
              <li class="nav-item mr-2">
                <%= link_to '新規登録', new_user_registration_path, class: "btn btn-light" %>
              </li>
              <li class="nav-item mr-2">
                <%= link_to 'ログイン', new_user_session_path, class: "btn btn-light" %>
              </li>
              <li class="nav-item mr-2">
                <%= link_to '管理者ログイン', new_admin_session_path, class: "btn btn-light" %>
              </li>
              <li class="nav-item mr-0">
                <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, {method: "post", class: "btn btn-light "} %>
              </li>
            <% end %>
          </ul>
        </div>
    </nav>
    
    <% if user_signed_in? %>
    <div class="row">
      <div class="col-md-2 mt-5">
        <%= render "public/searches/category_search" %>
      </div>
    <% end %>
        <%= yield %>
    </div>
    
    <div class='container py-3 mb-5 mt-5'></div>
      <footer class="fixed-bottom text-center">
        <div class="container">
          <p style="color: #aaa;">&copy; 2023 FPS BEGINNER</p>
        </div>
      </footer>
  </body>
</html>